version: '3'
services:

  backend:
    image: "zvone99/movie-app:latest-backend"
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  frontend:
    image: "zvone99/movie-app:latest-frontend"
    container_name: frontend
    ports:
      - "3000:3000"
    links:
      - backend